[general]
name = "gmp-fix"
version = "0.3.0"

[build]
files = ["gmpz.fix"]
dynamic_links = ["gmp"]

[build.test]
files = ["test.fix"]
memcheck = true

[[dependencies]]
name = "hash"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }
