[general]
name = "gmp-fix"
version = "0.6.1"

[build]
files = ["gmpz.fix", "gmpq.fix"]
dynamic_links = ["gmp"]

[build.test]
files = ["test.fix", "gmpz-test.fix", "gmpq-test.fix"]
memcheck = true

[[dependencies]]
name = "hash"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }
