[general]
name = "gmp-fix"
version = "0.1.3"

[build]
files = ["gmpz.fix"]
# files = ["gmpz.fix", "gmpq.fix"]
dynamic_links = ["gmp"]
# static_links = ["gmpfix"]
# library_paths = ["."]
# preliminary_commands = [["make", "libgmpfix.a", "--quiet"]]

[build.test]
files = ["test.fix"]
memcheck = true

[[dependencies]]
name = "hash"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }
